### ISSUE TITLE
ee.py中load_data方法好像有些问题

### ISSUE THREAD

**Issue by tianjie491** [bojone/lic2020_baselines#2]
感谢苏神给出的rematch方法。
def load_data(filename):
    D = []
    with open(filename) as f:
        for l in f:
            l = json.loads(l)
            arguments = {}
            for event in l['event_list']:
                for argument in event['arguments']:
                    key = argument['argument']
                    value = (event['event_type'], argument['role'])
                    arguments[key] = value
            D.append((l['text'], arguments))
    return D
多个event_type的argument是同一个value时，arguments[key] = value后面的value会覆盖前面的。以event_type+role作为key，是否会好一些。

**Comment by bojone** [comment]
本baseline结合评价指标，将事件抽取转化为序列标注任务，而常规的序列标注本身就只是一对一的（一个实体只有一种类型），所以只好这样处理。如果要保留一对多的数据，那么同时也要在模型上做相应的改进，这就留给大家发挥了。
